# Change 'comments' to true for Disqus comments
# disqus:
  # comments: false
  # disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-ID: 

menu:
- {name: 'Blog',   url: 'Exoomo.github.io'}
- {name: 'Archiv',   url: 'archiv.html'}
- {name: 'About',   url: 'about.html'}
- {name: 'Kontakt', url: 'contact.html'}
- {name: 'Impressum', url: 'impressum.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'github',     link: ''}
#- {icon: 'twitter',    link: ''}
- {icon: 'linkedin',   link: 'https://de.linkedin.com/in/marco-rost'}
- {icon: 'envelope',   link: 'm.r.avuf0@slmails.com'}
#- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
